import { UserProfile } from '@clerk/nextjs';

export default function UserProfilePage() {
  return (
    <div className="min-h-screen bg-gray-50 py-12">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900">Your Profile</h1>
          <p className="mt-2 text-gray-600">
            Manage your account settings, security preferences, and personal information.
          </p>
        </div>

        <div className="bg-white shadow rounded-lg">
          <UserProfile
            appearance={{
              elements: {
                formButtonPrimary: 'bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded-md transition-colors duration-200',
                card: 'bg-transparent shadow-none',
                headerTitle: 'text-2xl font-bold text-gray-900',
                headerSubtitle: 'text-gray-600',
                formFieldInput: 'border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent',
                formFieldLabel: 'text-sm font-medium text-gray-700',
                formFieldLabelRow: 'mb-1',
                formFieldErrorText: 'text-red-600 text-sm mt-1',
                alertText: 'text-red-600 text-sm',
                alert: 'bg-red-50 border border-red-200 rounded-md p-3 mb-4',
                pageScrollBox: 'p-6',
                navbar: 'border-b border-gray-200 bg-gray-50',
                navbarButton: 'text-gray-600 hover:text-blue-600 font-medium py-2 px-3 rounded-md transition-colors',
                navbarButtonActive: 'text-blue-600 bg-blue-50',
                formSectionTitle: 'text-lg font-semibold text-gray-900',
                formSectionSubtitle: 'text-gray-600',
                badge: 'bg-blue-100 text-blue-800 text-xs font-medium px-2.5 py-0.5 rounded-full',
                avatarBox: 'w-20 h-20',
                avatarImage: 'rounded-full',
                formFieldAction: 'text-blue-600 hover:text-blue-700 font-medium',
                formFieldActionRow: 'mt-2',
                dividerLine: 'bg-gray-300',
                dividerText: 'text-gray-500 bg-white px-2',
                formFieldInputShowPasswordButton: 'text-gray-500 hover:text-gray-700',
                formResendCodeLink: 'text-blue-600 hover:text-blue-700',
                identityPreviewText: 'text-gray-600',
                identityPreviewEditButton: 'text-blue-600 hover:text-blue-700',
                modalBackdrop: 'bg-black bg-opacity-50',
                modalContent: 'bg-white rounded-lg shadow-xl',
                modalCloseButton: 'text-gray-400 hover:text-gray-600',
                formFieldRow: 'space-y-2',
                formField: 'space-y-1',
                formFieldInputRow: 'relative',
                formFieldHintText: 'text-gray-500 text-sm',
                formFieldSuccessText: 'text-green-600 text-sm',
                formFieldWarningText: 'text-yellow-600 text-sm',
                formFieldInfoText: 'text-blue-600 text-sm',
                formFieldSelect: 'border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent',
                formFieldTextarea: 'border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent',
                formFieldCheckbox: 'h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded',
                formFieldRadio: 'h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300',
                formFieldSwitch: 'relative inline-flex h-6 w-11 items-center rounded-full bg-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2',
                formFieldSwitchThumb: 'inline-block h-4 w-4 transform rounded-full bg-white transition',
                formFieldSwitchTrack: 'relative inline-flex h-6 w-11 items-center rounded-full bg-gray-200',
                formFieldSwitchTrackActive: 'bg-blue-600',
                formFieldSwitchTrackInactive: 'bg-gray-200',
                formFieldSwitchThumbActive: 'translate-x-6',
                formFieldSwitchThumbInactive: 'translate-x-1',
                formFieldSwitchLabel: 'ml-3 text-sm font-medium text-gray-700',
                formFieldSwitchLabelRow: 'flex items-center',
                formFieldSwitchLabelText: 'text-sm font-medium text-gray-700',
                formFieldSwitchLabelDescription: 'text-sm text-gray-500',
                formFieldSwitchLabelDescriptionRow: 'mt-1',
                formFieldSwitchLabelDescriptionText: 'text-sm text-gray-500',
                formFieldSwitchLabelDescriptionIcon: 'text-gray-400',
                formFieldSwitchLabelDescriptionIconRow: 'flex items-center space-x-1',
                formFieldSwitchLabelDescriptionIconText: 'text-sm text-gray-500',
                formFieldSwitchLabelDescriptionIconIcon: 'h-4 w-4',
                formFieldSwitchLabelDescriptionIconIconRow: 'flex-shrink-0',
                formFieldSwitchLabelDescriptionIconIconSvg: 'h-4 w-4 text-gray-400',
                formFieldSwitchLabelDescriptionIconIconPath: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconCircle: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconRect: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconPolygon: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconLine: 'stroke-current',
                formFieldSwitchLabelDescriptionIconIconPolyline: 'stroke-current',
                formFieldSwitchLabelDescriptionIconIconPath2: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconCircle2: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconRect2: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconPolygon2: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconLine2: 'stroke-current',
                formFieldSwitchLabelDescriptionIconIconPolyline2: 'stroke-current',
                formFieldSwitchLabelDescriptionIconIconPath3: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconCircle3: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconRect3: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconPolygon3: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconLine3: 'stroke-current',
                formFieldSwitchLabelDescriptionIconIconPolyline3: 'stroke-current',
                formFieldSwitchLabelDescriptionIconIconPath4: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconCircle4: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconRect4: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconPolygon4: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconLine4: 'stroke-current',
                formFieldSwitchLabelDescriptionIconIconPolyline4: 'stroke-current',
                formFieldSwitchLabelDescriptionIconIconPath5: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconCircle5: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconRect5: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconPolygon5: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconLine5: 'stroke-current',
                formFieldSwitchLabelDescriptionIconIconPolyline5: 'stroke-current',
                formFieldSwitchLabelDescriptionIconIconPath6: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconCircle6: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconRect6: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconPolygon6: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconLine6: 'stroke-current',
                formFieldSwitchLabelDescriptionIconIconPolyline6: 'stroke-current',
                formFieldSwitchLabelDescriptionIconIconPath7: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconCircle7: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconRect7: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconPolygon7: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconLine7: 'stroke-current',
                formFieldSwitchLabelDescriptionIconIconPolyline7: 'stroke-current',
                formFieldSwitchLabelDescriptionIconIconPath8: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconCircle8: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconRect8: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconPolygon8: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconLine8: 'stroke-current',
                formFieldSwitchLabelDescriptionIconIconPolyline8: 'stroke-current',
                formFieldSwitchLabelDescriptionIconIconPath9: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconCircle9: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconRect9: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconPolygon9: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconLine9: 'stroke-current',
                formFieldSwitchLabelDescriptionIconIconPolyline9: 'stroke-current',
                formFieldSwitchLabelDescriptionIconIconPath10: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconCircle10: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconRect10: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconPolygon10: 'fill-current',
                formFieldSwitchLabelDescriptionIconIconLine10: 'stroke-current',
                formFieldSwitchLabelDescriptionIconIconPolyline10: 'stroke-current',
              },
              layout: {
                socialButtonsPlacement: 'bottom',
                showOptionalFields: false,
                privacyPageUrl: '/privacy',
                termsPageUrl: '/terms',
              },
            }}
            path="/user-profile"
            routing="path"
          />
        </div>
      </div>
    </div>
  );
}
